// Auto-generated by generate_device_keys.sh - do not edit
export const DEVICE_PUBLIC_KEY_PEM = n\`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl/ZQSKDMxdwRlJBdYM5g
NqgquXbyVWqi45bMTKwvuwulIEBZr1y9YK5KCrzA7hZfUBk5CDaPd+QRqZ0vB1dC
ZIopnFgQqIR/TomhYbl+OD4xScVdfTrEixgGq5ZfyIfOVRr8AF9FbWGz3QsK53Kp
Au7HdDcs1tsksKaYxQlizbisKcLbAEq2YdNhGn9ZK+b180Cpt+POOwkKMXGJX1pU
k/7nsq+Bc2PGJYiMpoNa9MxR7WfxZhmjU6xCbbO+cddwIHTpUbT2lkfVi26x8xZ4
RiUT6XdKQC0QtcXX3ac+GPQpxEYcYpw1kRW5JNSIOgnenc75uEa6vhBfuo/h82pK
gwIDAQAB
-----END PUBLIC KEY-----\`;
