/*
 * ===============================================================================
 * (c) HTBLA Leonding 2024 - 2026
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Licensed under MIT License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the license.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * All trademarks used in this document are property of their respective owners.
 * ===============================================================================
 */

import fs from 'fs/promises';
import path from 'path';

async function main() {
  const cwd = process.cwd();
  const defaultInput = path.resolve(cwd, '..', 'embedded', 'keys', 'device_public.pem');
  const inputPath = process.argv[2] ? path.resolve(process.argv[2]) : defaultInput;
  const outPath = process.argv[3] ? path.resolve(process.argv[3]) : path.resolve(cwd, 'src', 'config', 'devicePublicKey.ts');

  try {
    const data = await fs.readFile(inputPath, 'utf8');
    const content = `// Auto-generated by embedDevicePublicKey.js - do not edit\nexport const DEVICE_PUBLIC_KEY_PEM = ` + '`' + `${data.replace(/`/g, '\\`')}` + '`' + `;\n`;
    await fs.mkdir(path.dirname(outPath), { recursive: true });
    await fs.writeFile(outPath, content, 'utf8');
    console.log('Embedded device public key into', outPath);
  } catch (err) {
    console.warn('Device public key not found at', inputPath, '\nWriting placeholder file to', outPath);
    const placeholder = `// Auto-generated placeholder\nexport const DEVICE_PUBLIC_KEY_PEM = ` + '`' + `-----BEGIN PUBLIC KEY-----\nREPLACE_WITH_DEVICE_PUBLIC_KEY\n-----END PUBLIC KEY-----` + '`' + `;\n`;
    await fs.mkdir(path.dirname(outPath), { recursive: true });
    await fs.writeFile(outPath, placeholder, 'utf8');
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
