#ifndef VERSION_H
#define VERSION_H

// This file is auto-generated by GitHub Actions during release builds
// For development builds, it shows the development version

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "1.0.1-dev"
#endif

#ifndef GIT_COMMIT_HASH
#define GIT_COMMIT_HASH "unknown"
#endif

#endif // VERSION_H
