#!/usr/bin/env bash
set -euo pipefail

# Generate a fresh RSA keypair and embed into firmware + web config

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
embedded_dir="$(cd "$script_dir/.." && pwd)"
keys_dir="$embedded_dir/keys"
private_pem="$keys_dir/device_private.pem"
public_pem="$keys_dir/device_public.pem"
device_private_header="$embedded_dir/src/DevicePrivateKey.h"
web_public_ts="$embedded_dir/../web/src/config/devicePublicKey.ts"

mkdir -p "$keys_dir"
mkdir -p "$(dirname "$device_private_header")"
mkdir -p "$(dirname "$web_public_ts")"

echo "Generating device RSA keypair..."
openssl genpkey -algorithm RSA -out "$private_pem" -pkeyopt rsa_keygen_bits:2048
openssl rsa -pubout -in "$private_pem" -out "$public_pem"

# Escape newlines for C string literal
escaped_private=$(awk '{printf("%s\\n", $0)}' "$private_pem")

cat > "$device_private_header" <<EOF
/*
 * ===============================================================================
 * (c) HTBLA Leonding 2024 - 2026
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * Licensed under MIT License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the license.
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * All trademarks used in this document are property of their respective owners.
 * ===============================================================================
 */


#pragma once

static const char DEVICE_PRIVATE_KEY_PEM[] = "$escaped_private";
EOF

echo "Writing web public key: $web_public_ts"
public_key_content=$(cat "$public_pem")
{
	printf '%s\n' '// Auto-generated by generate_device_keys.sh - do not edit'
	printf '%s' 'export const DEVICE_PUBLIC_KEY_PEM = '\n
	printf '%s' '\`'
	printf '%s' "$public_key_content"
	printf '%s\n' '\`;'
} > "$web_public_ts"

exit 0
